api:
  email: "cole.szeman@jax.org"
  ensembl_base_url: "https://rest.ensembl.org"
  interpro_base_url: "https://www.ebi.ac.uk/interpro/api/entry/pfam/"
  mousemine_base_url: "https://www.mousemine.org/mousemine/service/query/results"
  ols_base_url: "https://www.ebi.ac.uk/ols4/api/"

paths:
  clinvar_vcf: "data/NCBI/clinvar.grch38.vcf.gz"
  mgi_alleles: "data/MGI/VARIANT-ALLELE-MGI.tsv"
  mgi_homology: "data/MGI/HOM_ProteinCoding.rpt"
  mgi_disease: "data/MGI/MGI_DiseaseMouseModel.rpt"
  doid_map: "data/DOID/doid_map.json"
  mouse_gene_pqt: "data/Ensembl/mouse_gene_data.parquet"
  human_gene_pqt: "data/Ensembl/human_gene_data.parquet"

logging:
  file: "mapping.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

