name: MGI_Variant_Mapping
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pandas
  - biopython
  - requests
  - pip
  - pip:
      - pyensembl
      - pyarrow==21.0.0